name: social_app
description: An app similar to many other social apps

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart:
  redux_saga:
  flutter_redux:
  redux:
  dartz:
  freezed_annotation:
  google_fonts:
  flutter_svg:
     
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:

  flutter_lints: ^1.0.0
  build_runner:

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/